# cloudbuild.yaml para deploy de Google Cloud Functions (2nd Gen)

steps:
  # Etapa 1: Fazer build completo do projeto
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests'
      - '-Dquarkus.package.type=uber-jar' # Garante que o uber-jar seja criado
      - '-Dquarkus.package.jar.enabled=true'

  # Etapa 2: Listar conteúdo do diretório 'target' para depuração
  - name: 'ubuntu'
    entrypoint: 'ls'
    args:
      - '-R'
      - 'target'

  # Etapa 3: Deploy da função HTTP
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldHttpFunction'
      - '--source=.'
      - '--runtime=java21'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--region=${_REGION}'
      - '--project=${PROJECT_ID}'
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldHttpFunction'
      - '--gen2'

  # Etapa 4: Criar tópico do Pub/Sub (se não existir)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'pubsub'
      - 'topics'
      - 'create'
      - 'hello-world-topic'
      - '--project=${PROJECT_ID}'
    allow_failure: true  # Permite falha se o tópico já existir

  # Etapa 5: Deploy da função Background (agora com o gatilho correto de Storage)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldBackgroundFunction'
      - '--source=.'
      - '--runtime=java21'
      - '--trigger-event=google.storage.object.finalize'
      - '--trigger-resource=hello-world-bucket' # Adicionado recurso do trigger
      - '--region=${_REGION}'
      - '--project=${PROJECT_ID}'
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldBackgroundFunction'
      - '--gen2'

  # Etapa 6: Deploy da função Cloud Events (agora com o gatilho correto de Pub/Sub)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldCloudEventsFunction'
      - '--source=.'
      - '--runtime=java21'
      - '--trigger-topic=hello-world-topic' # Trocado para o gatilho de tópico
      - '--region=${_REGION}'
      - '--project=${PROJECT_ID}'
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldCloudEventsFunction'
      - '--gen2'

# Configuração de logging para o build
logsBucket: 'gs://default-postech-fiap-build-logs'
