# cloudbuild-native.yaml: Build nativo e deploy no Cloud Functions (Gen 2) via Docker

steps:
  # 1. Compila o executável nativo. Este passo é demorado.
  - name: 'maven:3.9.6-eclipse-temurin-21'
    id: 'Build Native Executable'
    entrypoint: 'mvn'
    args: ['package', '-Pnative', '-DskipTests']

  # 2. Constrói a imagem Docker e a envia para o Artifact Registry.
  # O campo 'images' cuida do push automático após o build.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and Push Docker Image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '.'
    images:
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

  # 3. Implanta a HelloWorldHttpFunction a partir da imagem Docker.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy HTTP Function'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldHttpFunction'
      - '--gen2'
      - '--region=${_REGION}'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--docker-image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest' # <-- USA A IMAGEM
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldHttpFunction' # <-- DIZ QUAL CLASSE USAR

  # 4. Implanta a HelloWorldBackgroundFunction a partir da mesma imagem Docker.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Background Function'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldBackgroundFunction'
      - '--gen2'
      - '--region=${_REGION}'
      - '--trigger-event=google.storage.object.finalize'
      - '--trigger-resource=hello-world-bucket'
      - '--docker-image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest' # <-- USA A MESMA IMAGEM
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldBackgroundFunction' # <-- DIZ QUAL CLASSE USAR

  # 5. Implanta a HelloWorldCloudEventsFunction a partir da mesma imagem Docker.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy CloudEvents Function'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldCloudEventsFunction'
      - '--gen2'
      - '--region=${_REGION}'
      - '--trigger-topic=hello-world-topic'
      - '--docker-image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest' # <-- USA A MESMA IMAGEM
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldCloudEventsFunction' # <-- DIZ QUAL CLASSE USAR

# Variáveis de substituição que serão usadas no pipeline
substitutions:
  _SERVICE_NAME: 'serveless-test-pubsub'
  _AR_REPO: 'my-apps' # O nome do repositório que você criou no Passo 1
  _REGION: 'southamerica-east1'

# Aumenta o timeout padrão, pois a compilação nativa pode demorar
timeout: '1800s' # 30 minutos