# cloudbuild-native.yaml: Build nativo e deploy no Cloud Functions (Gen 2) via Docker

# Substituições necessárias (defina na execução do build)
# _REGION=us-central1
# _REPOSITORY=cloud-run-source-deploy
# _SERVICE_NAME=serveless-test-pubsub-native

steps:
  # 1. Compila o executável nativo.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Native Executable'
    entrypoint: 'docker'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '-v'
      - '/usr/bin/docker:/usr/bin/docker'
      - '-v'
      - '/workspace:/workspace'
      - '-w'
      - '/workspace'
      - 'maven:3.9.6-eclipse-temurin-21'
      - 'mvn'
      - 'package'
      - '-Pnative'
      - '-DskipTests'
      - '-Dquarkus.netty.native-image-compute-allocator-config=true'

  # 2. Constrói a imagem Docker final usando BuildKit.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Final Docker Image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # 2.1. Criar repositório Artifact Registry se não existir
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Create Artifact Registry'
    entrypoint: 'gcloud'
    args:
      - 'artifacts'
      - 'repositories'
      - 'create'
      - '${_REPOSITORY}'
      - '--repository-format=docker'
      - '--location=${_REGION}'
      - '--project=${PROJECT_ID}'
    allow_failure: true  # Permite falha se o repositório já existir

  # 3. Implanta a HelloWorldHttpFunction a partir da imagem Docker.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy HTTP Function'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldHttpFunction'
      - '--gen2'
      - '--region=${_REGION}'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--docker-registry=artifact-registry'
      - '--docker-repository=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}'
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldHttpFunction'

  # 4. Implanta a HelloWorldBackgroundFunction a partir da mesma imagem Docker.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Background Function'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldBackgroundFunction'
      - '--gen2'
      - '--region=${_REGION}'
      - '--trigger-event=google.storage.object.finalize'
      - '--trigger-resource=hello-world-bucket'
      - '--docker-registry=artifact-registry'
      - '--docker-repository=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}'
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldBackgroundFunction'

  # 5. Implanta a HelloWorldCloudEventsFunction a partir da mesma imagem Docker.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy CloudEvents Function'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldCloudEventsFunction'
      - '--gen2'
      - '--region=${_REGION}'
      - '--trigger-topic=hello-world-topic'
      - '--docker-registry=artifact-registry'
      - '--docker-repository=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}'
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldCloudEventsFunction'

# O Cloud Build fará o push automático desta imagem para o Artifact Registry no final.
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

# Aumenta o timeout padrão, pois a compilação nativa pode demorar
timeout: '1800s' # 30 minutos

# Configuração de logging para o build
logsBucket: 'gs://default-postech-fiap-build-logs'
