steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'serveless-test-pubsub'
  - '--gen2'
  - '--runtime=java21'
  - '--region=europe-west1' # Região do seu gatilho original
  - '--source=.'
  - '--entry-point=io.quarkus.gcp.functions.QuarkusHttpFunction'
  - '--trigger-http'
  - '--allow-unauthenticated'
