# cloudbuild-native.yaml: Build nativo e deploy no Cloud Functions (Gen 2) via Docker

steps:
  # 1. Compila o executável nativo. Este passo é demorado.
  - name: 'maven:3.9.6-eclipse-temurin-21'
    id: 'Build Native Executable'
    entrypoint: 'mvn'
    args: ['package', '-Pnative', '-DskipTests']

  # 2. Constrói a imagem Docker. O push será feito no final pelo Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:latest'
      - '.'

  # 3. Implanta a HelloWorldHttpFunction a partir da imagem Docker.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy HTTP Function'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldHttpFunction'
      - '--gen2'
      - '--region=${_REGION}'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--docker-image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:latest'
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldHttpFunction'

  # 4. Implanta a HelloWorldBackgroundFunction a partir da mesma imagem Docker.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Background Function'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldBackgroundFunction'
      - '--gen2'
      - '--region=${_REGION}'
      - '--trigger-event=google.storage.object.finalize'
      - '--trigger-resource=hello-world-bucket'
      - '--docker-image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:latest'
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldBackgroundFunction'

  # 5. Implanta a HelloWorldCloudEventsFunction a partir da mesma imagem Docker.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy CloudEvents Function'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldCloudEventsFunction'
      - '--gen2'
      - '--region=${_REGION}'
      - '--trigger-topic=hello-world-topic'
      - '--docker-image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:latest'
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldCloudEventsFunction'

# O Cloud Build fará o push automático desta imagem para o Artifact Registry no final.
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:latest'

# Aumenta o timeout padrão, pois a compilação nativa pode demorar
timeout: '1800s' # 30 minutos

# Configuração de logging para o build
logsBucket: 'gs://default-postech-fiap-build-logs'