# ARQUIVO DE DIAGNÓSTICO TEMPORÁRIO
# O objetivo deste build é apenas listar o conteúdo do diretório 'target'
# para entendermos o que o Maven está gerando.

steps:
  # Etapa 1: Build da aplicação com Maven
  - name: 'maven:3.9.6-eclipse-temurin-21'
    id: 'Build'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests'

  # Etapa 2: Listar o conteúdo do diretório 'target'
  # Isso nos mostrará exatamente quais arquivos e JARs foram criados.
  - name: 'ubuntu'
    id: 'Diagnose'
    entrypoint: 'ls'
    args:
      - '-lR'
      - 'target'
