# cloudbuild.yaml para deploy de Google Cloud Functions

steps:
  # Etapa 1: Fazer build e deploy direto das funções para Google Cloud Functions
  # O Quarkus gera automaticamente os arquivos necessários para o deploy
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests'
      - '-Dquarkus.google-cloud-functions.deploy=true'
      - '-Dquarkus.google-cloud-functions.project-id=${PROJECT_ID}'
      - '-Dquarkus.google-cloud-functions.region=${_REGION}'

# Configuração de logging para o build
logsBucket: 'gs://default-postech-fiap-build-logs'
