# cloudbuild.yaml para deploy de Google Cloud Functions (2nd Gen) - Build Nativo

steps:
  # Etapa 1: Fazer build nativo do projeto Quarkus (executável nativo para Cloud Functions)
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'package'
      - '-DskipTests'
      - '-Pnative'
      - '-Dquarkus.native.enabled=true'
      - '-Dquarkus.package.jar.enabled=false'
      - '-Dquarkus.native.container-build=true'
      - '-Dquarkus.native.container-runtime=docker'
      - '-Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21'
    volumes:
      - name: 'docker'
        path: '/var/run/docker.sock'

  # Etapa 2: Build da imagem Docker nativa
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/serveless-test-pubsub-native:${COMMIT_SHA}'
      - '.'

  # Etapa 3: Push da imagem para GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/serveless-test-pubsub-native:${COMMIT_SHA}'

  # Etapa 4: Deploy da função HTTP usando container nativo
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldHttpFunction'
      - '--docker-registry=gcr.io'
      - '--docker-repository=${PROJECT_ID}/serveless-test-pubsub-native'
      - '--docker-tag=${COMMIT_SHA}'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--region=${_REGION}'
      - '--project=${PROJECT_ID}'
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldHttpFunction'
      - '--gen2'

  # Etapa 5: Criar tópico do Pub/Sub para Background Function (se não existir)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'pubsub'
      - 'topics'
      - 'create'
      - 'hello-world-topic'
      - '--project=${PROJECT_ID}'
    allow_failure: true  # Permite falha se o tópico já existir

  # Etapa 6: Deploy da função Background usando container nativo
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldBackgroundFunction'
      - '--docker-registry=gcr.io'
      - '--docker-repository=${PROJECT_ID}/serveless-test-pubsub-native'
      - '--docker-tag=${COMMIT_SHA}'
      - '--trigger-topic=hello-world-topic'
      - '--region=${_REGION}'
      - '--project=${PROJECT_ID}'
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldBackgroundFunction'
      - '--gen2'

  # Etapa 7: Deploy da função Cloud Events usando container nativo
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'HelloWorldCloudEventsFunction'
      - '--docker-registry=gcr.io'
      - '--docker-repository=${PROJECT_ID}/serveless-test-pubsub-native'
      - '--docker-tag=${COMMIT_SHA}'
      - '--trigger-event=google.storage.object.finalize'
      - '--trigger-resource=hello-world-bucket'
      - '--region=${_REGION}'
      - '--project=${PROJECT_ID}'
      - '--entry-point=com.postech.fiap.googlecloudfunctions.HelloWorldCloudEventsFunction'
      - '--gen2'

# Configuração de logging para o build
logsBucket: 'gs://default-postech-fiap-build-logs'
